networks:
  gitea:
    external: false

services:
  init:
    image: alpine:latest
    container_name: gitea_runner_init
    restart: "no"
    volumes:
      - ./:/source
      - gitea-runner-data:/data
      - gitea-runner-config:/config
  runner:
    image: docker.io/gitea/act_runner:latest
    container_name: gitea_runner
    environment:
      GITEA_INSTANCE_URL: "${GITEA_INSTANCE_URL}"
      GITEA_RUNNER_REGISTRATION_TOKEN: "${REGISTRATION_TOKEN}"
      CONFIG_FILE: /config/config.yaml
    volumes:
      - ./config.yaml:/source/config.yaml
      - gitea-runner-data:/data
      - gitea-runner-config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - init

volumes:
  gitea-runner-data:
  gitea-runner-config:
