networks:
  gitea:
    external: false

services:
  init:
    image: alpine:latest
    container_name: gitea_runner_init
    command: >
      sh -c "ls -la"
    restart: "no"
    volumes:
      - .:/source
  runner:
    image: docker.io/gitea/act_runner:latest
    container_name: gitea_runner
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: "${GITEA_INSTANCE_URL}"
      GITEA_RUNNER_REGISTRATION_TOKEN: "${REGISTRATION_TOKEN}"
    volumes:
      - ./data:/data
      - ./config.yaml:/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - init

volumes:
  gitea-runner-data:
