networks:
  gitea:
    external: false

services:
  init:
    image: alpine/git
    command: clone https://github.com/dbahlbeck/homelab.git /config
    volumes:
      - config-data:/config

  runner:
    image: docker.io/gitea/act_runner:latest
    container_name: gitea_runner
    environment:
      GITEA_INSTANCE_URL: "${GITEA_INSTANCE_URL}"
      GITEA_RUNNER_REGISTRATION_TOKEN: "${REGISTRATION_TOKEN}"
      CONFIG_FILE: /config/gitea_runner/config.yaml
    volumes:
      - /:/source
      - gitea-runner-data:/data
      - config-data:/config
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - init

volumes:
  gitea-runner-data:
  config-data:
