services:
  init:
    image: eclipse-mosquitto:latest
    command: "mosquitto_passwd -c -b /mosquitto/config/pwfile ${username} ${password}"
    restart: "no"
    volumes:
      - mosquitto-data:/mosquitto

  clone:
    image: alpine/git
    entrypoint: sh
    command: >
      git clone https://github.com/dbahlbeck/homelab.git /tmp/repo &&
      cp -r /tmp/repo/mqtt/* /config
    volumes:
      - mosquitto-data:/config


  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1884:1883"
      - "9002:9001"
    volumes:
      - mosquitto-data:/mosquitto
    restart: unless-stopped
    depends_on:
      - init
      - clone

volumes:
  mosquitto-data:
    external: true