services:
  init:
    image: eclipse-mosquitto:latest
    command: "mosquitto_passwd -c -b /mosquitto/config/pwfile ${username} ${password}"
    restart: "no"
    volumes:
      - mosquitto-data:/mosquitto

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9002:9001"
    volumes:
      - mosquitto-data:/mosquitto
    restart: unless-stopped
    depends_on:
      - init
      - clone

volumes:
  mosquitto-data:
    external: true