services:
  init:
    image: alpine
    container_name: ha-init
    restart: no
    volumes:
      - ha_config:/config
    entrypoint: ["/bin/sh", "-c"]
    command: |
      set -e
      apk add --no-cache git
      git clone https://github.com/dbahlbeck/homelab.git /tmp/repo
      mkdir -p /config/config
      cp /tmp/repo/homeassistant/configuration.yaml /config/config/
      echo "Init complete"

#  homeassistant:
#    image: ghcr.io/home-assistant/home-assistant:stable
#    container_name: homeassistant
#    restart: unless-stopped
#    volumes:
#      - ha_config:/config
#      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - "8123:8123"
volumes:
  ha_config: